layout_spectrum: 0.1833022
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.8619403
  brandColors:
    - '#FEFEFE'
    - '#23A8ED'
    - '#59595B'
    - '#DC4248'
    - '#070508'
  rhythmicContrast: 1
typography_spectrum: 0.47738
name: Wild About Websites
