layout_spectrum: 0
color:
  saturation: 0.224347
  lightness: 1
  brandStrength: 0.1296642
  brandColors:
    - '#FFFFFF'
    - '#03A7EF'
    - '#3FBCF3'
    - '#63C8F5'
    - '#9EDAF8'
  rhythmicContrast: 1
typography_spectrum: 0.47738
name: Wild About Websites
